<?php
$word = array(
"https://i.imgur.com/4M1u1w7.mp4",
"https://i.imgur.com/2C03Lz3.mp4",
"https://i.imgur.com/rVeN8jx.mp4",
"https://i.imgur.com/pJED07p.mp4",
"https://i.imgur.com/DjJb7cB.mp4",
"https://i.imgur.com/DjJb7cB.mp4",
"https://i.imgur.com/hhpeUqY.mp4",
"https://i.imgur.com/hhpeUqY.mp4",
"https://i.imgur.com/7MrfYrF.mp4",
"https://i.imgur.com/2c3EN37.mp4",
"https://i.imgur.com/4Pf4Gt5.mp4",
"https://i.imgur.com/R92YWvA.mp4",
"https://i.imgur.com/7kARxdM.mp4",
"https://i.imgur.com/PIKWn2R.mp4",
"https://i.imgur.com/FGPJ0pN.mp4",
"https://i.imgur.com/OGYyVLS.mp4",
"https://i.imgur.com/1w4WVDV.mp4",
"https://i.imgur.com/S80tPmG.mp4",
"https://i.imgur.com/pMj8BXy.mp4",
"https://i.imgur.com/ItsvJjW.mp4",
"https://imgur.com/d9QlIBX.mp4",
  "https://i.imgur.com/5AkEWL7.mp4",
  "https://imgur.com/MX6wo8d.mp4",
  "https://i.imgur.com/RTL7xbI.mp4",
  "https://i.imgur.com/sgujKjs.mp4",
  "https://i.imgur.com/R9K7SHf.mp4",
  "https://i.imgur.com/2cB5bv3.mp4",
  "https://i.imgur.com/Go6UiIk.mp4",
  "https://i.imgur.com/5WZvVAT.mp4",
  "https://i.imgur.com/Zz4Clog.mp4",
  "https://imgur.com/oF5JjSi.mp4",
  "https://imgur.com/MxilxON.mp4",
  "https://imgur.com/gPDKOlp.mp4",
  "https://i.imgur.com/xjoutvc.mp4",
  "https://imgur.com/DNK8Fgx.mp4",
  "https://i.imgur.com/twqISpH.mp4",
  "https://i.imgur.com/U0d9QLY.mp4",
  "https://i.imgur.com/HNf37tk.mp4",
  "https://i.imgur.com/JVCBCPw.mp4",
  "https://imgur.com/I6RG0wO.mp4",
  "https://i.imgur.com/0fthfKk.mp4",
  "https://i.imgur.com/Bc7csE2.mp4",
  "https://i.imgur.com/964TBf2.mp4",
  "https://i.imgur.com/5DlYBn7.mp4",
  "https://i.imgur.com/4XYhDLw.mp4",
  "https://i.imgur.com/0JeRFCP.mp4",
  "https://i.imgur.com/0doC2Oo.mp4",
  "https://i.imgur.com/9GePJTH.mp4",
  "https://i.imgur.com/EQ2BJOq.mp4",
  "https://i.imgur.com/qna7u0f.mp4",
  "https://i.imgur.com/EVVMxZL.mp4",
  "https://i.imgur.com/1PESGXL.mp4",
  "https://imgur.com/AstY6pb.mp4",
  "https://i.imgur.com/DNlv5AY.mp4",
  "https://i.imgur.com/upcdaUS.mp4",
  "https://i.imgur.com/YdNjX4C.mp4",
  "https://i.imgur.com/ATEJcwt.mp4",
  "https://i.imgur.com/BjAUlsx.mp4",
  "https://imgur.com/RLhREXj.mp4",
  "https://imgur.com/8M4GVtg.mp4",
  "https://i.imgur.com/XG71Uol.mp4",
"https://i.imgur.com/VtEkKg7.mp4", 
"https://i.imgur.com/rL3t3yF.mp4", 
"https://i.imgur.com/2TGiGG6.mp4",
"https://i.imgur.com/uVLKSQi.mp4",
"https://i.imgur.com/UKUbWgz.mp4", 
"https://i.imgur.com/aGs88rb.mp4", 
"https://i.imgur.com/UqSpEdy.mp4", 
"https://i.imgur.com/j0qlcLM.mp4", 
"https://i.imgur.com/BozKte6.mp4", 
"https://i.imgur.com/pryUgck.mp4", 
"https://i.imgur.com/ZyoZuap.mp4", 
"https://i.imgur.com/np9Qb7r.mp4", 
"https://i.imgur.com/j2XeI1N.mp4", 
"https://i.imgur.com/1qXqlG1.mp4",
"https://imgur.com/8M4GVtg.mp4",
  "https://imgur.com/MX6wo8d.mp4",
  "https://i.imgur.com/CfKc79R.mp4",
  "https://i.imgur.com/EVVMxZL.mp4",
  "https://imgur.com/I6RG0wO.mp4",
  "https://i.imgur.com/9GePJTH.mp4",
  "https://imgur.com/BVkWb0p.mp4",
  "https://i.imgur.com/5WcyZav.mp4",
  "https://i.imgur.com/xjoutvc.mp4",
  "https://imgur.com/77YOJSi.mp4",
  "https://i.imgur.com/BjAUlsx.mp4",
  "https://i.imgur.com/0fthfKk.mp4",
  "https://i.imgur.com/4XYhDLw.mp4",
  "https://imgur.com/ExlxR0J.mp4",
  "https://imgur.com/TXHf7G2.mp4",
  "https://i.imgur.com/eDTPlSH.mp4",
  "https://i.imgur.com/EQ2BJOq.mp4",
  "https://i.imgur.com/2cB5bv3.mp4",
  "https://i.imgur.com/No7JxtI.mp4",
  "https://i.imgur.com/DNlv5AY.mp4",
  "https://i.imgur.com/YdNjX4C.mp4",
  "https://i.imgur.com/twqISpH.mp4",
  "https://i.imgur.com/U0d9QLY.mp4",
  "https://i.imgur.com/964TBf2.mp4",
  "https://i.imgur.com/RTL7xbI.mp4",
  "https://imgur.com/MxilxON.mp4",
  "https://i.imgur.com/ATEJcwt.mp4",
  "https://i.imgur.com/HeZklaD.mp4",
  "https://imgur.com/AstY6pb.mp4",
  "https://i.imgur.com/5WZvVAT.mp4",
  "https://imgur.com/gPDKOlp.mp4",
  "https://i.imgur.com/5DlYBn7.mp4",
  "https://imgur.com/DNK8Fgx.mp4",
  "https://i.imgur.com/HNf37tk.mp4",
  "https://i.imgur.com/upcdaUS.mp4",
  "https://i.imgur.com/1PESGXL.mp4",
  "https://i.imgur.com/0doC2Oo.mp4"
  );
$api = array_rand($word);
$apivip = $word [$api];
$loli = array(
"data" => $apivip,
"count" => count($word),
"author" => "I'mZ",
);
$rdimg = json_encode($loli , JSON_UNESCAPED_UNICODE);

$i = ['\/v\/','\/'];
$t = ['/v/','/'];
$j = str_replace($i, $t, $rdimg);
echo $j;