<?php
$word = array(
  "https://i.imgur.com/CAuLPHl.jpg",
"https://i.imgur.com/DqA0ouX.jpg",
"https://i.imgur.com/hPO06VQ.jpg",
"https://i.imgur.com/goy1GBH.jpg",
"https://i.imgur.com/BOJKZUE.jpg",
"https://i.imgur.com/m1OMT2j.jpg",
"https://i.imgur.com/V8NaFMd.jpg",
"https://i.imgur.com/NwKF3yI.jpg",
"https://i.imgur.com/pR81zDn.jpg",
"https://i.imgur.com/5G3Itdn.jpg",
"https://i.imgur.com/njMMuQ7.jpg",
"https://i.imgur.com/6Ngd1SU.jpg",
"https://i.imgur.com/ctYKMCm.jpg",
"https://i.imgur.com/ksRWehD.jpg",
"https://i.imgur.com/ZIRL0aZ.jpg",
"https://i.imgur.com/vwzxWv2.jpg",
"https://i.imgur.com/AsJGvyC.jpg",
"https://i.imgur.com/C6zNiiz.jpg",
"https://i.imgur.com/QTfuIna.jpg",
"https://i.imgur.com/usy7Zyo.jpg",
"https://i.imgur.com/IQ7GZh8.jpg",
"https://i.imgur.com/465OEoB.jpg",
"https://i.imgur.com/P0dZ0eN.jpg",
"https://i.imgur.com/N0IfovL.jpg",
"https://i.imgur.com/Dk0gdlB.jpg",
"https://i.imgur.com/NOkTzXp.jpg",
"https://i.imgur.com/fMbQmGd.jpg",
"https://i.imgur.com/HPiNvkw.jpg",
"https://i.imgur.com/84z6lH4.jpg",
"https://i.imgur.com/C5ceG4L.jpg",
"https://i.imgur.com/92LxHyX.jpg",
"https://i.imgur.com/WRvXlHn.jpg",
"https://i.imgur.com/LQ5K5O6.jpg",
"https://i.imgur.com/POeLTXt.jpg",
"https://i.imgur.com/SFavCw1.jpg",
"https://i.imgur.com/IjaYUOm.jpg",
"https://i.imgur.com/UZEtzIW.jpg",
"https://i.imgur.com/40Ev89g.jpg",
"https://i.imgur.com/2jwDiU0.jpg",
"https://i.imgur.com/VS9V2nA.jpg",
"https://i.imgur.com/x3va1XD.jpg",
"https://i.imgur.com/GLNVV9y.jpg",
"https://i.imgur.com/HrJzEX5.jpg",
"https://i.imgur.com/khD1vQ9.jpg",
"https://i.imgur.com/WvSWgdB.jpg",
"https://i.imgur.com/WcoTYng.jpg",
"https://i.imgur.com/FNm80S2.jpg",
"https://i.imgur.com/9kUMYKb.jpg",
"https://i.imgur.com/JN7jfwd.jpg",
"https://i.imgur.com/Ay9A9LZ.jpg",
"https://i.imgur.com/0Xlfcc8.jpg",
"https://i.imgur.com/nnMjzAc.jpg",
"https://i.imgur.com/m7rJON9.jpg",
"https://i.imgur.com/la8M2kO.jpg",
"https://i.imgur.com/OtZ3ROZ.jpg",
"https://i.imgur.com/3mfjc54.jpg",
"https://i.imgur.com/PRrl5CH.jpg",
"https://i.imgur.com/6p10KZz.jpg",
"https://i.imgur.com/XluxrZ7.jpg",
"https://i.imgur.com/LBanKCM.jpg",
"https://i.imgur.com/CWG47oF.jpg",
"https://i.imgur.com/CUDtQwA.jpg",
"https://i.imgur.com/AwDO9Ci.jpg",
"https://i.imgur.com/6HVDbvc.jpg",
"https://i.imgur.com/EsIHwYr.jpg",
"https://i.imgur.com/dO7m8kx.jpg",
"https://i.imgur.com/twplQ78.jpg",
"https://i.imgur.com/TZiAScr.jpg",
"https://i.imgur.com/5AsQqhO.jpg",
"https://i.imgur.com/HiLO2Jm.jpg",
"https://i.imgur.com/y1lbl62.jpg",
"https://i.imgur.com/OWxLU06.jpg",
"https://i.imgur.com/gCqxBn7.jpg",
"https://i.imgur.com/vffwqek.jpg",
"https://i.imgur.com/rlNVL0Z.jpg",
"https://i.imgur.com/8HdRPSR.jpg",
"https://i.imgur.com/BadJgk0.jpg",
"https://i.imgur.com/RiPIusQ.jpg",
"https://i.imgur.com/3GLhxWI.jpg",
"https://i.imgur.com/dICrOGL.jpg",
"https://i.imgur.com/0j3UenS.jpg",
"https://i.imgur.com/sI8cc1u.jpg",
"https://i.imgur.com/2kmqhWp.jpg",
"https://i.imgur.com/OXYaVTF.jpg",
"https://i.imgur.com/HQW2mEy.jpg",
"https://i.imgur.com/RYuYEDQ.jpg",
"https://i.imgur.com/fG8wD57.jpg",
"https://i.imgur.com/mR5mg4A.jpg",
"https://i.imgur.com/UcQImL4.jpg",
"https://i.imgur.com/pY8mYaL.jpg",
"https://i.imgur.com/J2iehXP.jpg",
"https://i.imgur.com/cEAMruB.jpg",
"https://i.imgur.com/y1gHr04.jpg",
"https://i.imgur.com/ndu13vY.jpg",
"https://i.imgur.com/aAnPbsw.jpg",
"https://i.imgur.com/ybv4wL9.jpg",
"https://i.imgur.com/k05p0ht.jpg",
"https://i.imgur.com/Vxo1VXm.jpg",
"https://i.imgur.com/5wGWLIs.jpg",
"https://i.imgur.com/xaVJL76.jpg",
"https://i.imgur.com/ZO4bpAI.jpg",
"https://i.imgur.com/HNhPlCZ.jpg",
"https://i.imgur.com/YflfgUA.jpg",
"https://i.imgur.com/ocpxkXx.jpg",
"https://i.imgur.com/CDmBKMW.jpg",
"https://i.imgur.com/OMUp085.jpg",
"https://i.imgur.com/equq7bL.jpg",
"https://i.imgur.com/OxXUyTi.jpg"
);
$api = array_rand($word);
$apivip = $word [$api];
$loli = array(
"data" => $apivip,
"count" => count($word),
"author" => "I'mZ",
);
$rdimg = json_encode($loli , JSON_UNESCAPED_UNICODE);

$i = ['\/v\/','\/'];
$t = ['/v/','/'];
$j = str_replace($i, $t, $rdimg);
echo $j;