<?php
$word = array(
      "https://i.imgur.com/82WnYOQ.jpg",
    "https://i.imgur.com/jhHfWRR.jpg",
    "https://i.imgur.com/79sqZKV.jpg",
    "https://i.imgur.com/xwA74fH.jpg",
    "https://i.imgur.com/BSLPoCh.jpg",
    "https://i.imgur.com/M6lrtzB.jpg",
    "https://i.imgur.com/gUChlAv.jpg",
    "https://i.imgur.com/q1g3kpU.jpg",
    "https://i.imgur.com/F2butWY.jpg",
    "https://i.imgur.com/zLGVWIS.jpg",
    "https://i.imgur.com/OxKWANi.jpg",
    "https://i.imgur.com/BeXYjXd.jpg",
    "https://i.imgur.com/oaAnfPH.jpg",
    "https://i.imgur.com/iaBM3xb.jpg",
    "https://i.imgur.com/xPDpEoK.jpg",
    "https://i.imgur.com/qlckEo6.jpg",
    "https://i.imgur.com/W8Ls4bA.jpg",
    "https://i.imgur.com/GBgoem1.jpg",
    "https://i.imgur.com/VTXEt1K.jpg",
    "https://i.imgur.com/6J1BFBI.jpg",
    "https://i.imgur.com/EJWamt0.jpg",
    "https://i.imgur.com/pQcn1Ub.jpg",
    "https://i.imgur.com/wpT6BbJ.jpg",
    "https://i.imgur.com/DnQJWYG.jpg",
    "https://i.imgur.com/g2DLyBJ.jpg",
    "https://i.imgur.com/6BpEKx7.jpg",
    "https://i.imgur.com/gEni8tT.jpg",
    "https://i.imgur.com/q3pGCWD.jpg",
    "https://i.imgur.com/O97ogrZ.jpg",
    "https://i.imgur.com/DCpLVdt.jpg",
    "https://i.imgur.com/vrUOfbt.jpg",
    "https://i.imgur.com/cm01Kex.jpg",
    "https://i.imgur.com/Sr7mAB1.jpg",
    "https://i.imgur.com/V8qvTjY.jpg",
    "https://i.imgur.com/WMF8ldw.jpg",
    "https://i.imgur.com/wutXmTP.jpg",
    "https://i.imgur.com/9S70TGE.jpg",
    "https://i.imgur.com/JsAzb7x.jpg",
    "https://i.imgur.com/uQzSGh6.jpg",
    "https://i.imgur.com/p4fLrtk.jpg",
    "https://i.imgur.com/R3yt72V.jpg",
    "https://i.imgur.com/kOU5nd2.jpg",
    "https://i.imgur.com/eIrNumq.jpg",
    "https://i.imgur.com/0ANoi2t.jpg",
    "https://i.imgur.com/D9ahgb2.jpg",
    "https://i.imgur.com/zrQ4uN3.jpg",
    "https://i.imgur.com/jC4bBJ4.jpg",
    "https://i.imgur.com/Xnzamxr.jpg",
    "https://i.imgur.com/XgaBF9C.jpg",
    "https://i.imgur.com/2aTmzkR.jpg",
    "https://i.imgur.com/yu1a88C.jpg",
    "https://i.imgur.com/Fern81O.jpg",
    "https://i.imgur.com/2x698nn.jpg",
    "https://i.imgur.com/fOM3ZPe.jpg",
    "https://i.imgur.com/kJT5KzT.jpg",
    "https://i.imgur.com/qBVq8Rw.jpg",
    "https://i.imgur.com/ZjsThZy.jpg",
    "https://i.imgur.com/sooHBsP.jpg",
    "https://i.imgur.com/lJflvbd.jpg",
    "https://i.imgur.com/XvsNz3V.jpg",
    "https://i.imgur.com/ctwlLsh.jpg",
    "https://i.imgur.com/2zY6VQ2.jpg",
    "https://i.imgur.com/rm1o5RR.jpg",
    "https://i.imgur.com/0GdLzQv.jpg",
    "https://i.imgur.com/dEDhcpO.jpg",
    "https://i.imgur.com/4J8xl2l.jpg",
    "https://i.imgur.com/5PZnAEB.jpg",
    "https://i.imgur.com/0KtBxlJ.jpg",
    "https://i.imgur.com/T6Huu72.jpg",
    "https://i.imgur.com/Wn3jEvf.jpg",
    "https://i.imgur.com/oQ2uAeV.jpg",
    "https://i.imgur.com/d1E2LDC.jpg",
    "https://i.imgur.com/YmV2lAO.jpg",
    "https://i.imgur.com/1tHyVFC.jpg",
    "https://i.imgur.com/Ei96AEW.jpg",
    "https://i.imgur.com/gB3SiWR.jpg",
    "https://i.imgur.com/8kEeTl7.jpg",
    "https://i.imgur.com/Ygy4bYL.jpg",
    "https://i.imgur.com/xfu5RY1.jpg",
    "https://i.imgur.com/gtWtZQV.jpg",
    "https://i.imgur.com/QBPubgc.jpg",
    "https://i.imgur.com/cdik9hu.jpg",
    "https://i.imgur.com/90po0UY.jpg",
    "https://i.imgur.com/Q9kYNns.jpg",
    "https://i.imgur.com/MJ6Dv5a.jpg",
    "https://i.imgur.com/KN3JL4A.jpg",
    "https://i.imgur.com/OyNz9wC.jpg",
    "https://i.imgur.com/SVUE3gh.jpg",
    "https://i.imgur.com/pbf4RY2.jpg",
    "https://i.imgur.com/vmABGOx.jpg",
    "https://i.imgur.com/WuVqvkO.jpg",
    "https://i.imgur.com/2pwMUsj.jpg"
);
$api = array_rand($word);
$apivip = $word [$api];
$loli = array(
"data" => $apivip,
"count" => count($word),
"author" => "I'mZ",
);
$rdimg = json_encode($loli , JSON_UNESCAPED_UNICODE);

$i = ['\/v\/','\/'];
$t = ['/v/','/'];
$j = str_replace($i, $t, $rdimg);
echo $j;