<?php
$word = array(
"https://i.imgur.com/QCjcaDp.jpg",
      "https://i.imgur.com/PYmWnbU.jpg",
    "https://i.imgur.com/PM7tvHm.jpg",
    "https://i.imgur.com/mpKPXYG.jpg",
    "https://i.imgur.com/d4ObrJn.jpg",
    "https://i.imgur.com/J9vlz3k.jpg",
    "https://i.imgur.com/lFhjSC2.jpg",
    "https://i.imgur.com/M3QoVAu.jpg",
    "https://i.imgur.com/RIFFIZb.jpg",
    "https://i.imgur.com/p6IrMEU.jpg",
    "https://i.imgur.com/rFDasMD.jpg",
    "https://i.imgur.com/LoS1Bhd.jpg",
    "https://i.imgur.com/J2eI3ZT.jpg",
    "https://i.imgur.com/oSgcNb5.jpg",
    "https://i.imgur.com/UsVCJUU.jpg",
    "https://i.imgur.com/wAlIgTm.jpg",
    "https://i.imgur.com/vqpyuJP.jpg",
    "https://i.imgur.com/Ri3Zg9V.jpg",
    "https://i.imgur.com/sGkuxqM.jpg",
    "https://i.imgur.com/h7Byey2.jpg",
    "https://i.imgur.com/D0W8wVP.jpg",
    "https://i.imgur.com/2LTHuIT.jpg",
    "https://i.imgur.com/YaeXhQc.jpg",
    "https://i.imgur.com/u4Jd0Qu.jpg",
    "https://i.imgur.com/RiPlTEB.jpg",
    "https://i.imgur.com/MoxEFYx.jpg",
    "https://i.imgur.com/OGTAyIO.jpg",
    "https://i.imgur.com/gXcCa8F.jpg",
    "https://i.imgur.com/e5VVe3k.jpg",
    "https://i.imgur.com/vRgSwG7.jpg",
    "https://i.imgur.com/ws8bwXU.jpg",
    "https://i.imgur.com/o6hJIeO.jpg",
    "https://i.imgur.com/T1qLiAQ.jpg",
    "https://i.imgur.com/Q0WY4Ld.jpg",
    "https://i.imgur.com/5ReMbj3.jpg",
    "https://i.imgur.com/9rNjVCw.jpg",
    "https://i.imgur.com/pWuh1dd.jpg",
    "https://i.imgur.com/9o40gnb.jpg",
    "https://i.imgur.com/AYwyldr.jpg",
    "https://i.imgur.com/6ZgDRGY.jpg",
    "https://i.imgur.com/JwSjZY2.jpg",
    "https://i.imgur.com/vOc4hS5.jpg",
    "https://i.imgur.com/nLpHkOU.jpg",
    "https://i.imgur.com/Pyhy1rQ.jpg",
    "https://i.imgur.com/111pYRC.jpg",
    "https://i.imgur.com/TrREmvZ.jpg",
    "https://i.imgur.com/J7GvJpH.jpg",
    "https://i.imgur.com/m0oDIK5.jpg",
    "https://i.imgur.com/npLP61l.jpg",
    "https://i.imgur.com/f9ALlm9.jpg",
    "https://i.imgur.com/txCyQP4.jpg",
    "https://i.imgur.com/WFsSvTL.jpg",
    "https://i.imgur.com/ut3pa0j.jpg",
    "https://i.imgur.com/WoZG4QS.jpg",
    "https://i.imgur.com/Akr2VqP.jpg",
    "https://i.imgur.com/QIvHIpw.jpg",
    "https://i.imgur.com/FwYVfjR.jpg",
    "https://i.imgur.com/rSKDn8A.jpg",
    "https://i.imgur.com/YZCJwwO.jpg",
    "https://i.imgur.com/iQ6tX1x.jpg",
    "https://i.imgur.com/EBErOcP.jpg",
    "https://i.imgur.com/HXXluf9.jpg",
    "https://i.imgur.com/kIRCTZP.jpg",
    "https://i.imgur.com/bkV1w0I.jpg",
    "https://i.imgur.com/Kkk6cab.jpg",
    "https://i.imgur.com/xpnXpZQ.jpg",
    "https://i.imgur.com/5Baemai.jpg",
    "https://i.imgur.com/Q8LI1Kl.jpg",
    "https://i.imgur.com/8oJdo1l.jpg",
    "https://i.imgur.com/h5l9SgK.jpg",
    "https://i.imgur.com/ByFnZCI.jpg",
    "https://i.imgur.com/OgKP4BV.jpg",
    "https://i.imgur.com/USmwJLn.jpg",
    "https://i.imgur.com/PIgZdoH.jpg",
    "https://i.imgur.com/6uKcYkX.jpg",
    "https://i.imgur.com/M01Zhwc.jpg",
    "https://i.imgur.com/jDzkked.jpg",
    "https://i.imgur.com/67Tw3go.jpg",
    "https://i.imgur.com/AykhuY7.jpg",
    "https://i.imgur.com/PZbeIFS.jpg",
    "https://i.imgur.com/YWOLxzA.jpg",
    "https://i.imgur.com/b4BqbBG.jpg",
    "https://i.imgur.com/SuJWY2I.jpg",
    "https://i.imgur.com/vx0wE75.jpg",
    "https://i.imgur.com/odp3Grg.jpg"
  );
$api = array_rand($word);
$apivip = $word [$api];
$loli = array(
"data" => $apivip,
"count" => count($word),
"author" => "I'mZ",
);
$rdimg = json_encode($loli , JSON_UNESCAPED_UNICODE);

$i = ['\/v\/','\/'];
$t = ['/v/','/'];
$j = str_replace($i, $t, $rdimg);
echo $j;